---
# tasks file for do_create_droplet
- name: Get SSH Key ID
  uri:
    url: https://api.digitalocean.com/v2/account/keys
    method: GET
    return_content: yes
    headers: 
      Content-Type: application/json
      Authorization: Bearer {{ do_api }}
  register: do_keys_request

- name: create a new droplet
  digital_ocean_droplet:
    state: present
    name: "{{ droplet_hostname }}"
    oauth_token: "{{ do_api }}"
    size: "{{ droplet_size }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    ssh_keys: "{{ do_keys_request.json.ssh_keys[0].id }}"
    wait_timeout: 500
  register: my_droplet

- name: add hosts
  add_host:
    name: "{{ my_droplet.data.ip_address }}"
    groups: "do"

- name: wait for droplet boot up
  wait_for:
    port: 22
    host: "{{ my_droplet.data.ip_address }}"
    timeout: 30
    delay: 10

- name: grab ssh-key
  shell: ssh-keyscan -t ECDSA {{ my_droplet.data.ip_address }} >> ~/.ssh/known_hosts
  register: my_droplet_ssh